service: historial

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  environment:
    CHARACTER_TABLE: ${param:characterTable}
    API_PREFIX: ${env:API_PREFIX}
    API_VERSION: ${env:API_VERSION}
  tracing:
    lambda: true
  apiGateway:
    restApiId: ${param:restApiId}
    restApiRootResourceId: ${param:restApiRootResourceId}
    apiKeySourceType: HEADER
  iamRoleStatements:
    - Effect: Allow
      Action:
        - "xray:PutTraceSegments"
        - "xray:PutTelemetryRecords"
      Resource: "*"
    - Effect: Allow
      Action: 
        - "dynamodb:Scan"
      Resource: "${param:characterTable}"

plugins:
  - serverless-plugin-include-dependencies

functions:
  historial:
    name: historial
    handler: dist/main.handler    
    timeout: 15
    memorySize: 256
    events:
      - http:
          path: ""
          method: get
          private: true
          authorizer: 
            type: COGNITO_USER_POOLS
            authorizerId: ${param:authorizer}
            scopes: 
              - openid


package:
  excludeDevDependencies: false
  patterns:
    - '!**'    
    - 'dist/**'   
    - '!dist'   
    - '!node_modules/aws-sdk/**'

