service: api-gw-softtek
provider:
  name: aws
  runtime: nodejs20.x
  stage: dev
  region: us-east-1
resources:
  Resources:
    MyApiGW:
      Type: AWS::ApiGateway::RestApi
      Properties:
        Name: api-gw-softtek
    DummyResource:
        Type: AWS::ApiGateway::Resource
        Properties:
          RestApiId: !Ref MyApiGW
          ParentId: !GetAtt
            - MyApiGW
            - RootResourceId
          PathPart: dummy
    DummyMethod:
      Type: AWS::ApiGateway::Method
      Properties:
        RestApiId: !Ref MyApiGW
        ResourceId: !Ref DummyResource
        HttpMethod: GET
        AuthorizationType: NONE
        Integration:
          Type: MOCK
          RequestTemplates:
            application/json: '{ "statusCode": 200 }'
          IntegrationResponses:
            - StatusCode: 200
              ResponseTemplates:
                application/json: '{ "message": "Hello, this is a dummy response!" }'
        MethodResponses:
          - StatusCode: 200
            ResponseModels:
              application/json: "Empty"
    MyUserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        UserPoolName: MyUserPool
        AutoVerifiedAttributes:
          - email
        MfaConfiguration: OFF
        Policies:
          PasswordPolicy:
            MinimumLength: 8
            RequireLowercase: true
            RequireNumbers: true
            RequireSymbols: true
            RequireUppercase: true
    MyUserPoolClient:
      Type: AWS::Cognito::UserPoolClient
      DependsOn: MyUserPool
      Properties:
        ClientName: MyAppClient
        UserPoolId:
          Ref: MyUserPool
        AllowedOAuthFlows:
          - code
        AllowedOAuthScopes:
          - email
          - openid
          - profile
        AllowedOAuthFlowsUserPoolClient: true
        CallbackURLs:
          - "http://localhost:3000/callback"
        LogoutURLs:
          - "http://localhost:3000/logout"
        SupportedIdentityProviders:
          - COGNITO
        ExplicitAuthFlows:
          - ALLOW_USER_PASSWORD_AUTH
          - ALLOW_REFRESH_TOKEN_AUTH
    MyApiGatewayAuthorizer:
      DependsOn:
        - MyUserPool
        - MyApiGW
      Type: AWS::ApiGateway::Authorizer
      Properties:
        Name: MyCognitoAuthorizer
        Type: COGNITO_USER_POOLS
        IdentitySource: 'method.request.header.Authorization'
        RestApiId:
          Ref: MyApiGW
        AuthorizerResultTtlInSeconds: 300
        ProviderARNs:
          - Fn::GetAtt: [MyUserPool, Arn]
    CognitoUserPoolDomain:
      DependsOn: 
        - MyUserPool
      Type: AWS::Cognito::UserPoolDomain
      Properties:
        Domain: ${env:COGNITO_DOMAIN}
        UserPoolId: 
          Ref: MyUserPool
    ApiResource:
      Type: AWS::ApiGateway::Resource
      Properties:
        RestApiId: !Ref MyApiGW
        ParentId: !GetAtt
          - MyApiGW
          - RootResourceId
        PathPart: "${env:API_PREFIX}"
    VersionResource:
      Type: AWS::ApiGateway::Resource
      Properties:
        RestApiId: !Ref MyApiGW
        ParentId: !Ref ApiResource
        PathPart: "${env:API_VERSION}"
    AlmacenarResource:
      Type: AWS::ApiGateway::Resource
      Properties:
        RestApiId: !Ref MyApiGW
        ParentId: !Ref VersionResource
        PathPart: "almacenar"
    FusionadosResource:
      Type: AWS::ApiGateway::Resource
      Properties:
        RestApiId: !Ref MyApiGW
        ParentId: !Ref VersionResource
        PathPart: "fusionados"
    HistorialResource:
      Type: AWS::ApiGateway::Resource
      Properties:
        RestApiId: !Ref MyApiGW
        ParentId: !Ref FusionadosResource
        PathPart: "historial"
    FusionadosParamResource:
      Type: AWS::ApiGateway::Resource
      Properties:
        RestApiId: !Ref MyApiGW
        ParentId: !Ref FusionadosResource
        PathPart: "{name}"
  Outputs:
    appCognitoPoolId:
      Value: !Ref MyUserPool
    appClientId:
      Value: !Ref MyUserPoolClient
      Description: The App Client ID
    apiGatewayRestApiId:
      Value:
        Ref: MyApiGW
      Export:
        Name: MyApiGateway-restApiId
    apiHistorialParamResourceVar:
      Value: !Ref HistorialResource
      Export:
        Name: !Sub ${AWS::StackName}-ApiFusionadosResourceVar
    apiFusionadosParamResourceVar:
      Value: !Ref FusionadosParamResource
      Export:
        Name: !Sub ${AWS::StackName}-ApiFusionadosParamResourceVar
    apiAlmacenarParamResourceVar:
      Value: !Ref AlmacenarResource
      Export:
        Name: !Sub ${AWS::StackName}-ApiAlmacenarParamResourceVar
    apiAuthorizerArn:
      Value: !Ref MyApiGatewayAuthorizer
      Export:
        Name: MyApiGatewayAuthorizer
